# values-minikube.yaml
# This example intended as baseline to use Minikube for the deployment of GitLab
# - Minimized CPU/Memory load, can fit into 3 CPU, 6 GB of RAM (barely)
# - Services that are not compatible with how Minikube runs are disabled
# - Some services entirely removed, or scaled down to 1 replica.
# - Configured to use 192.168.99.100, and nip.io for the domain

# Minimal settings
global:
  edition: ce
  ingress:
    configureCertmanager: false
    # Toggle the TCP configuration and annotations to Traefik.
    provider: traefik
    class: traefik

  hosts:
    https: false
    domain: localhost
    externalIP: localhost
  # Disable Rails bootsnap cache (temporary)
  rails:
    bootsnap:
      enabled: false
certmanager:
  install: false
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: false
# Save resources, only 3 CPU
prometheus:
  install: false
gitlab-runner:
  install: false
# Reduce replica counts, reducing CPU & memory requirements
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1

traefik:
  install: true
  # Ensure the IngressClass name and `global.ingress.class` value match.
  # This can be removed if `global.ingress.class` is set to `$releaseName-traefik`.
  fullnameOverride: traefik
  ingressClass:
    # Create an IngressClass object for Traefik.
    enabled: true
    # Helps an avoid error when making local templates.
    fallbackApiVersion: v1