Vagrant.configure("2") do |config|
  config.vm.hostname = "ybel-hacS"
  config.vm.box = "ubuntu/bionic64"
  config.vm.network :private_network, ip: "192.168.56.110"
  config.vm.provision :shell, path: './scripts/setupMachine.sh'
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end
end
