Vagrant.configure("2") do |config|
  config.vm.hostname = "ybel-hacS"
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.network :private_network, ip: "192.168.56.110"
  config.vm.provision :shell, path: './scripts/setupMachine.sh'
  config.vm.provider :vmware_desktop do |v|
    v.allowlist_verified = true
    v.gui = false
    v.vmx["numvcpus"] = "2"
    v.vmx["memsize"] = "1024"
  end
  # config.vm.provider "virtualbox" do |v|
  #   v.cpus = 1
  #   v.memory = 512
  # end
end
