Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define :server do |server|
    server.vm.hostname = "ybel-hacS"
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.provider :vmware_desktop do |v|
      v.allowlist_verified = true # tell vagrant to work only with verified versions of vmware fusion
      v.gui = false
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "1024"
    end
    # # for linux amd64 based
    # server.vm.provider "virtualbox" do |v|
    #   v.memory = 1024
    #   v.cpus = 1
    # end
    server.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  config.vm.define :serverWorker do |serverWorker|
    serverWorker.vm.hostname ="ybel-hacSW"
    serverWorker.vm.network :private_network, ip: "192.168.56.111"
    serverWorker.vm.provider :vmware_desktop do |v|
      v.allowlist_verified = true
      v.gui = false
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "512"
    end
    ## for linux amd64 based
    # serverWorker.vm.provider "virtualbox" do |v|
    #   v.memory = 512
    #   v.cpus = 1
    # end
    serverWorker.vm.provision :shell, inline: <<-SHELL
      NODE_TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$NODE_TOKEN sh -
    SHELL
  end
end